#服务器配置
server:
  #端口
  port: 8020

#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://localhost:9000/eureka

#spring配置
spring:
  #应用配置
  application:
    #名称: OAuth2认证授权服务
    name: auth-server
  #数据库配置
  data:
    mongodb:
#      url: mongodb://admin:123123@hd02:2700/auth_server
      port: 2717
      database: auth_server
      host: hd02
#      username: admin
#      password: 123123
  redis:
    host: hd02
    port: 6379

#安全配置
security:
  #oauth2配置
  oauth2:
    resource:
      filter-order: 3


